In [6]:
#fully connected network, input - hidden -outpu
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf

mnist = input_data.read_data_sets("/home/jst/share/project/udacity/code/deep_nn/minist", one_hot=True, reshape=False)
# Parameters
learning_rate = 0.001
training_epochs = 20
batch_size = 128  # Decrease batch size if you don't have enough memory
display_step = 1

n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

n_hidden_layer = 256 # layer number of features,隐层的神经元个数

# Store layers weight & bias
weights = {
    'hidden_layer': tf.Variable(tf.random_normal([n_input, n_hidden_layer])),
    'out': tf.Variable(tf.random_normal([n_hidden_layer, n_classes]))
}
biases = {
    'hidden_layer': tf.Variable(tf.random_normal([n_hidden_layer])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

# tf Graph input
x = tf.placeholder("float", [None, 28, 28, 1])
y = tf.placeholder("float", [None, n_classes])

x_flat = tf.reshape(x, [-1, n_input]) #二维图像扁平拉伸至一维数组

#定义网络结构
# Hidden layer with RELU activation
layer_1 = tf.add(tf.matmul(x_flat, weights['hidden_layer']),\
    biases['hidden_layer'])
layer_1 = tf.nn.relu(layer_1)
# Output layer with linear activation
logits = tf.add(tf.matmul(layer_1, weights['out']), biases['out'])

#定义损失函数及优化器SGD
# Define loss and optimizer
cost = tf.reduce_mean(\
    tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)\
    .minimize(cost)


# Initializing the variables
init = tf.global_variables_initializer()

#注意，这边的next_batch是mnist案例特有的，其他数据集要自己写
# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    # Training cycle
    for epoch in range(training_epochs):
        total_batch = int(mnist.train.num_examples/batch_size)
        # Loop over all batches
        for i in range(total_batch):
            batch_x, batch_y = mnist.train.next_batch(batch_size)
            # Run optimization op (backprop) and cost op (to get loss value)
            output = sess.run([optimizer,cost], feed_dict={x: batch_x, y: batch_y})
            print(output[1])


Extracting /home/jst/share/project/udacity/code/deep_nn/minist/train-images-idx3-ubyte.gz
Extracting /home/jst/share/project/udacity/code/deep_nn/minist/train-labels-idx1-ubyte.gz
Extracting /home/jst/share/project/udacity/code/deep_nn/minist/t10k-images-idx3-ubyte.gz
Extracting /home/jst/share/project/udacity/code/deep_nn/minist/t10k-labels-idx1-ubyte.gz
171.45065
199.44482
161.13618
165.1882
155.43524
148.59387
161.77336
150.61812
150.23615
147.88547
137.388
148.217
150.65933
135.47299
125.514694
144.03268
140.0732
132.91193
129.07837
137.84062
122.09407
127.76642
129.25943
124.988365
120.26489
122.8748
115.60467
117.341896
115.1433
116.11789
121.9192
115.64602
108.900406
113.65433
106.71657
101.58908
94.32182
106.60231
116.47814
107.69736
116.44165
107.321106
104.2097
107.747665
108.68788
105.55508
106.418045
90.564224
97.26593
102.59644
110.240875
103.75243
91.6298
107.61943
101.61852
97.31697
87.229614
109.19916
101.55387
94.95089
101.763504
103.968155
94.90304
94.01036
89.90418
8

22.898226
15.502266
26.022604
17.037544
24.694366
24.955467
22.206957
19.518206
25.165884
22.22291
17.504047
24.811905
25.604197
17.301062
24.127485
16.570423
23.364712
19.591047
20.470665
20.576172
24.25614
20.679604
25.621437
19.171951
17.567837
21.758656
21.975168
25.94738
25.909126
23.568256
21.506382
22.45608
23.225113
21.717487
19.867641
21.684057
17.621075
21.132256
27.698975
25.117172
17.754505
21.58001
20.503113
21.53313
19.139885
21.608099
18.242826
23.057777
16.453648
18.220377
25.422346
21.66167
20.427773
24.011261
21.953949
21.040703
21.54051
19.57944
15.773432
21.86222
20.624008
20.29712
19.939499
24.084587
19.900805
22.234856
24.838062
20.448273
25.68238
18.448057
21.297064
26.428198
21.95485
19.422764
20.397667
19.158535
18.528437
22.921019
16.725224
21.272028
16.09656
22.931673
19.050503
25.23265
20.05982
17.125072
24.698528
24.435658
15.77547
18.07592
15.546836
18.256512
19.003532
25.239758
22.33508
22.833246
19.86261
17.624823
20.822561
17.812326
17.733053
18.957783


14.211835
16.099348
15.817497
15.637926
23.191088
16.242023
11.25857
10.549749
16.818615
11.117615
17.849579
13.977621
19.128292
16.138075
14.936462
11.8103
18.9497
16.671368
10.113234
17.351131
16.762625
12.780275
13.013389
9.977801
11.02546
17.494019
18.049747
11.672124
20.030699
15.191145
9.993334
13.099077
10.379753
11.8278265
12.824626
13.988652
11.728773
12.525604
14.955383
13.252583
10.266254
12.717528
14.67889
12.454515
15.708155
17.000576
15.331932
9.988975
18.48329
16.736603
14.655473
13.245567
14.414435
13.791563
14.9309635
14.205288
13.567227
12.283788
19.11373
9.783764
15.38234
11.980668
16.514677
14.520915
13.029785
14.351782
13.523801
16.56593
13.72493
15.364684
11.3429
17.424994
14.531259
17.595028
17.080627
13.42732
15.678199
15.978831
12.382872
11.56939
12.004799
10.795082
16.77454
10.626659
16.275703
11.826922
12.193787
16.264233
14.971243
15.197812
16.71143
15.87484
18.678661
14.388978
15.18631
13.322069
7.9785633
17.466248
17.275772
10.912867
14.4434395
17.755524
1

11.09543
17.363512
13.921573
10.327904
9.950145
9.049004
14.493402
8.117932
13.804737
12.9753685
12.312346
13.076559
11.582268
11.1336155
14.79032
16.131893
12.031372
11.869354
9.161677
11.577344
14.992428
11.956286
15.815823
12.831435
6.7015467
10.724191
10.839939
14.740497
7.971939
10.277601
8.999333
10.697317
12.450682
10.508951
9.299337
17.030983
13.351304
9.947729
9.883453
10.31629
11.045601
8.4533415
10.589996
9.498725
6.84894
8.587346
12.159404
8.799995
13.325994
9.021687
12.758835
11.580755
10.187425
13.260532
15.250109
14.515572
15.57411
12.334857
11.168695
7.306484
15.216952
9.841094
12.212556
11.617226
11.861948
11.381037
10.543839
8.327076
10.322941
12.294089
12.262658
11.585259
12.756119
9.786911
14.981863
7.6587105
11.579151
12.051582
8.168751
10.787301
13.509983
9.680393
8.118866
11.117898
13.367651
8.570446
7.8888154
12.852287
11.1856575
13.582183
10.646074
8.1991005
8.686652
9.486696
7.731685
8.832902
13.525777
13.765104
8.22257
10.457639
9.306326
10.906364
9.778073
9.

8.713455
10.569866
10.3746195
11.622612
9.017082
7.752882
13.458724
9.816359
12.116283
8.894962
3.8004177
8.18109
9.597483
9.089769
11.922602
8.922154
11.946277
7.475085
13.979557
13.71643
9.643335
8.424189
9.515307
7.5682497
9.515779
9.583562
10.179956
10.254351
6.7717447
9.120497
13.594885
13.4851885
12.1815195
12.235006
13.921186
11.275042
9.227108
10.309996
11.519577
8.764662
5.3155146
10.178143
11.928566
7.4170313
7.29745
9.26348
9.678791
11.853878
9.949687
8.552602
7.703643
11.108351
10.384172
10.079951
8.297187
12.163338
8.543512
10.357188
11.880127
10.727769
10.598066
13.599531
11.133099
11.477009
11.951954
14.898312
8.583267
5.943521
7.928918
11.863573
5.3721704
12.947959
10.919161
6.936781
9.86148
11.391519
10.472829
10.936433
8.371202
12.178376
5.920265
8.610036
10.285458
11.18326
10.202646
8.006119
9.288498
11.9354
9.321256
15.172247
6.9369097
10.24489
11.970315
11.498268
11.795879
8.492203
11.208602
7.5591154
9.422573
12.340834
10.568163
12.911465
7.1900754
8.458378
9.0758

6.815501
8.842915
11.320678
11.557533
5.879429
9.76609
5.7466726
5.611363
10.553533
3.8657277
6.8222814
7.361145
11.615061
8.931082
7.708817
9.180868
7.687239
12.615118
7.8912354
9.569352
10.945493
9.772797
9.907694
10.17074
6.8348527
7.4410286
11.497181
6.938714
7.438003
11.177171
9.788802
7.5953064
9.078609
7.241409
4.822839
10.029716
10.363588
8.471727
13.310756
11.706793
10.105877
9.391015
6.452117
5.158593
8.333169
12.882851
7.694949
11.956064
8.688797
8.897201
5.1710725
10.702665
7.116413
7.450533
8.145892
8.57225
11.477534
10.080795
5.771598
7.463743
7.785207
8.59354
7.4853897
6.184531
9.507352
8.363063
11.72114
8.544388
11.0379505
9.469427
8.01405
9.5299225
8.702538
8.688166
9.502847
7.831603
8.793116
5.7916517
11.552959
6.2165403
7.8633137
7.8311987
13.724083
12.229082
5.7002316
8.728971
8.642136
9.629981
4.1224375
8.817069
11.990493
8.037185
9.666752
6.761078
6.3307657
5.3566723
8.545496
9.8780775
13.464585
6.7270517
6.8632154
5.403056
9.829941
6.5812874
11.123163
6.598711
8.

6.2978315
11.202105
5.431938
9.809385
8.88284
6.5976934
7.3940973
5.369931
5.7069263
6.3704963
10.1883955
4.6466312
6.613683
5.4038343
10.71782
4.504735
9.081064
7.1303782
6.3237123
11.613365
6.7304516
10.0347805
6.276488
5.964306
6.816912
5.755952
10.079073
7.769528
7.028021
11.480181
6.5156097
7.5082726
7.218607
6.8687725
9.830313
7.120954
7.743959
4.8869677
8.704807
7.9396124
6.869984
8.52802
5.571246
6.29106
5.271005
8.62309
8.874147
5.9576483
8.9417
7.4642706
5.236682
6.882122
4.053216
12.08113
8.662956
7.4540596
6.20176
4.349852
9.251464
5.6655827
9.43891
5.700672
6.6979375
7.2688212
5.8636947
6.199354
6.139905
7.9790764
6.3633633
8.178321
5.721409
10.104746
4.014233
9.655058
9.105649
6.84229
7.513048
8.692455
3.3468034
7.0309734
7.0710006
5.3905015
8.513789
6.720412
6.7991915
8.0956135
7.6132717
6.912032
10.752248
6.3971643
6.492184
7.5022144
9.87411
8.483352
7.450585
7.2059155
6.9997263
5.449831
10.795359
7.6499376
8.9750395
8.512359
7.0296116
10.631686
5.2426615
7.095994
6.569

7.53851
11.656521
8.150904
8.140536
9.401953
3.5873177
6.889505
5.0676513
5.4648304
9.284489
7.3199654
8.895548
8.213302
6.8108644
8.292987
6.692648
6.2334723
7.4747787
6.9697504
8.289233
7.004782
2.3175845
6.912121
7.4109197
5.6467476
4.514233
11.082624
8.190026
9.264591
6.884047
7.164448
7.868227
5.725295
6.360876
4.117143
5.347199
10.09974
7.45665
5.362126
9.072216
11.862671
8.564512
4.6729107
7.7251735
9.354246
3.9358263
7.431156
5.4865704
9.644643
8.416977
5.234371
4.43272
6.493256
6.3056235
12.716232
7.33257
6.7419972
7.459469
6.8422318
8.536609
6.381522
7.059681
7.886779
10.893473
5.3987417
7.6996837
7.843191
5.2860713
8.479614
6.6580667
9.44113
5.0027075
6.990554
5.144328
8.614067
6.310354
9.3222685
7.0984344
6.9464273
7.0040474
5.531882
6.9463882
6.1748433
4.421306
5.6552434
8.717611
7.151012
6.8092127
9.73936
7.1398196
5.830851
6.3719473
5.485217
3.3434877
6.6013403
6.171357
8.426196
7.002405
5.205066
8.68566
6.6648526
6.7022133
7.1092463
5.967491
5.575698
2.0382864
6.942396


6.171984
7.2179317
6.869535
6.591364
4.9734926
7.2322435
3.4882333
7.7280436
8.60889
6.494426
12.141478
9.248419
5.2164054
9.387497
8.1816845
6.6832914
11.11368
6.595306
9.2979355
8.584764
5.4885263
3.9092758
6.782503
8.574536
7.764503
7.6063657
6.804249
6.67862
8.2024975
5.0533376
8.177138
4.8263826
5.9210005
7.1985097
5.730423
3.4503663
7.3497066
10.442577
5.9013033
8.398367
10.043564
6.011463
6.2261267
4.7968497
4.43828
3.1194367
3.6542585
9.171719
4.0621314
7.358351
10.381633
5.7841415
9.353921
6.3973794
6.05645
4.074402
4.20271
5.063922
6.925854
8.051155
6.112245
7.7099595
5.5212345
5.461532
5.1352673
5.466583
6.95133
6.155836
5.359644
7.456437
9.40804
6.7053423
9.05987
4.5301805
5.906848
4.2060614
6.3800793
6.637386
3.9696157
6.871747
7.5106683
7.457789
10.390751
5.907407
9.149182
5.0599303
9.666067
5.8647137
5.4454374
7.674885
10.814569
6.4491205
4.2444434
8.506521
5.656197
5.3770022
4.240192
5.7654276
7.83751
3.064155
5.2376733
3.758171
3.5721548
7.4716997
8.489847
4.3582344
8.

In [10]:
#Save TensorFlow Models
import tensorflow as tf

# The file path to save the data
save_file = './model.ckpt'

# Two Tensor Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

with tf.Session() as sess:
    # Initialize all the Variables
    sess.run(tf.global_variables_initializer())

    # Show the values of weights and bias
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

    # Save the model
    saver.save(sess, save_file)


Weights:
[[-0.18705377  1.333855    1.6201172 ]
 [ 0.7339593   1.0908154  -0.72840595]]
Bias:
[-0.16868883  0.5125753   0.43655545]


In [11]:
#Loading Variables
import tensorflow as tf

# The file path to save the data
save_file = './model.ckpt'

# Remove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

with tf.Session() as sess:
    # Load the weights and bias
    saver.restore(sess, save_file)

    # Show the values of weights and bias
    print('Weight:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

INFO:tensorflow:Restoring parameters from ./model.ckpt
Weight:
[[-0.18705377  1.333855    1.6201172 ]
 [ 0.7339593   1.0908154  -0.72840595]]
Bias:
[-0.16868883  0.5125753   0.43655545]
